CREATE DATABASE GASMANAGER;

USE GASMANAGER;

CREATE TABLE CLIENTE(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
);

CREATE TABLE ENDERECO(
    ID_ENDERECO INT PRIMARY KEY AUTO_INCREMENT,
    BAIRRO VARCHAR(100) NOT NULL,
    RUA VARCHAR(100) NOT NULL,
    NUMERO VARCHAR(10) NOT NULL,
    REFERENCIA VARCHAR(100)
);

CREATE TABLE TELEFONE(
    ID_TELEFONE INT PRIMARY KEY AUTO_INCREMENT,
    TIPO_TELEFONE CHAR(3) NOT NULL,
    NUMERO VARCHAR(20) NOT NULL
);

CREATE TABLE PEDIDO(
    ID_PEDIDO INT PRIMARY KEY AUTO_INCREMENT,
    
);