CREATA DATABASE PRATICAS;
USE PRATICAS;
		
CREATE TABLE CATEGORY(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR(255) NOT NULL,
	TIER INT NOT NULL	
);
		
CREATE TABLE PRODUCT(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR(255) NOT NULL,
	PRICE FLOAT(10,2) NOT NULL,
	CATEGORY_ID INT,
	FOREIGN KEY(CATEGORY_ID) REFERENCES CATEGORY(ID)
);
		
INSERT INTO CATEGORY VALUES(NULL, 'TOOLS', 2);
INSERT INTO CATEGORY VALUES(NULL, 'COMPUTERS',1);
INSERT INTO CATEGORY VALUES(NULL, 'ELETRONICS', 1);
		
INSERT INTO PRODUCT VALUES(NULL, 'Computer', 1100.0, 1);
INSERT INTO PRODUCT VALUES(NULL, 'Hammer', 90.0, 2);
INSERT INTO PRODUCT VALUES(NULL, 'Smart TV', 1700.0, 1);
